if(EXISTS "/Users/zowo4540/Desktop/Codes/Github/orca/sdr/tests/test_utils[1]_tests.cmake")
  include("/Users/zowo4540/Desktop/Codes/Github/orca/sdr/tests/test_utils[1]_tests.cmake")
else()
  add_test(test_utils_NOT_BUILT test_utils_NOT_BUILT)
endif()
